apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: kube-honduras
  labels:
    component: elasticsearch
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: 3 #number of nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: managed-premium

  http:
    tls:
      selfSignedCertificate:
        disabled: true