apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-honduras
  namespace: kube-honduras
  labels:
    app: kibana-honduras
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: es-cluster
  config:
    server.basePath: /dashboard
  http:
    tls:
      selfSignedCertificate:
        disabled: true